Attribute VB_Name = "ImportingModule"
Sub ImportData1()
Attribute ImportData1.VB_ProcData.VB_Invoke_Func = " \n14"
'
' Importing data from a .csv file generated by Tool B:
' select the csv file using a file dialog
' import the file as a query table
' copy and paste columns in the query table to the main sheet, in a preset order
' delete the query table
'
    Dim fDialog As FileDialog, result As Integer
    Dim filepath As String
    Dim ws1 As Worksheet
    Dim ws2 As Worksheet
    Dim ws1rowStartNum As Long
    Dim ws2rowEndNum As Long
        
    'set "ws1" to be whatever sheet is active
    Set ws1 = ActiveSheet
    ws1rowStartNum = ws1.Range("B4").End(xlDown).Row + 1
        
    'set the properties of the file dialogue window
    Set fDialog = Application.FileDialog(3)
    fDialog.AllowMultiSelect = False
    fDialog.Title = "Select a file"
    fDialog.InitialFileName = "S:\Service and Development\Lab I\Process data workflow\161103 csv import\" 'default file search location
    fDialog.Filters.Clear
    fDialog.Filters.Add "Comma Separated Value files", "*.csv"
     
    'Show the dialog; -1 means success
    If fDialog.Show = -1 Then
        filepath = fDialog.SelectedItems(1)
        filepath = "TEXT;" & filepath
        
        'freeze the visible program
        Application.EnableEvents = False
        Application.ScreenUpdating = False
        Application.DisplayAlerts = False
       
        'create a new blank worksheet, "ws2"
        ActiveWorkbook.Worksheets.Add
        Set ws2 = ActiveSheet
        
        'import the file selected in the dialog window
        With ws2.QueryTables.Add( _
            Connection:=filepath, _
            Destination:=ws2.Range("$A$1"))
            .Name = "imported data"
            .FieldNames = True
            .RowNumbers = False
            .FillAdjacentFormulas = False
            .PreserveFormatting = True
            .RefreshOnFileOpen = False
            .RefreshStyle = xlOverwriteCells
            .SavePassword = False
            .SaveData = True
            .AdjustColumnWidth = True
            .RefreshPeriod = 0
            .TextFilePromptOnRefresh = False
            .TextFilePlatform = 437
            .TextFileStartRow = 4 'start the first row of data at this row
            .TextFileParseType = xlDelimited
            .TextFileTextQualifier = xlTextQualifierDoubleQuote
            .TextFileConsecutiveDelimiter = False
            .TextFileTabDelimiter = True
            .TextFileSemicolonDelimiter = False
            .TextFileCommaDelimiter = True
            .TextFileSpaceDelimiter = False
            .TextFileColumnDataTypes = Array(1, 9, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 1, 1, 9, 1, _
            9, 9, 9, 9, 9, 9, 1, 9, 1, 1, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9) 'xlSkipColumn = 9 (skip), xlGeneralFormat = 1 (keep)
            'only keep columns A C N O Q X Z AA from .csv file, set by this ^ array
            'setting the values to columns A B C D E F G H in ws2
            .TextFileTrailingMinusNumbers = True
            .Refresh BackgroundQuery:=False
        End With
        
        ws2rowEndNum = ws2.Range("A1").End(xlDown).Row
        
        Application.CutCopyMode = False
        ws2.Range("A1", Cells(ws2rowEndNum, 2)).Copy 'copy from A:B in ws2
        ws1.Activate
        ws1.Paste Destination:=ws1.Cells(ws1rowStartNum, 1) 'paste to A in ws1
            
        Application.CutCopyMode = False
        ws2.Activate
        ws2.Range("G1", Cells(ws2rowEndNum, 7)).Copy 'copy from G in ws2
        ws1.Activate
        ws1.Paste Destination:=ws1.Cells(ws1rowStartNum, 3) 'paste to C in ws1
        
        Application.CutCopyMode = False
        ws2.Activate
        ws2.Range("F1", Cells(ws2rowEndNum, 6)).Copy 'copy from F in ws2
        ws1.Activate
        ws1.Paste Destination:=ws1.Cells(ws1rowStartNum, 4) 'paste to D in ws1
        
        Application.CutCopyMode = False
        ws2.Activate
        ws2.Range("C1", Cells(ws2rowEndNum, 5)).Copy 'copy from C:E in ws2
        ws1.Activate
        ws1.Paste Destination:=ws1.Cells(ws1rowStartNum, 5) 'paste to E in ws1
        
        Application.CutCopyMode = False
        ws2.Activate
        ws2.Range("H1", Cells(ws2rowEndNum, 8)).Copy 'copy from H in ws2
        ws1.Activate
        ws1.Paste Destination:=ws1.Cells(ws1rowStartNum, 10) 'paste to J in ws1
        
        'Delete query table connections
        For Each Cn In ThisWorkbook.Connections
            Cn.Delete
        Next Cn
        For Each Cn In ws2.QueryTables
            Cn.Delete
        Next Cn
        
        'delete the sheet
        ws2.Delete
            
        'unfreeze the visible program
        Application.EnableEvents = True
        Application.ScreenUpdating = True
        Application.DisplayAlerts = True
        
    End If
    
End Sub


